include(ExternalProject)

set(ROMOCC_DOWNLOAD_DIR ${PROJECT_SOURCE_DIR}/external/)
set(ROMOCC_EXTERNAL_BUILD_DIR ${PROJECT_BINARY_DIR}/external/)
set(ROMOCC_EXTERNAL_INSTALL_DIR ${PROJECT_BINARY_DIR})
